-- =====================================================================
-- Dockly — 0001_init
-- Kaynak: docs/22-veritabani-mimarisi.md (FROZEN v2.0, 6 Temmuz 2026)
-- Fiziksel tek şema (public) — §1.9 izniyle, mantıksal modül ayrımı
-- yorumlarla belirtilir. Sıra (§10): extensions → enum'lar → lookup'lar
-- → geo → identity → catalog → community → booking/messaging/ops →
-- index'ler → trigger'lar.
-- RLS: Faz 2 (ADR-003)
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0. EXTENSIONS
-- ---------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------
-- 1. ENUM TİPLERİ (§3 — yalnızca 15 iş akışı durumu)
-- ---------------------------------------------------------------------
CREATE TYPE user_status AS ENUM ('active', 'suspended', 'deleted');
CREATE TYPE location_status AS ENUM ('draft', 'pending_review', 'published', 'archived');
CREATE TYPE moderation_status AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE moderation_entity AS ENUM ('media', 'review', 'suggested_location', 'location_report');
CREATE TYPE reservation_request_status AS ENUM ('pending', 'contacted', 'confirmed', 'cancelled_by_user', 'cancelled_by_ops', 'expired');
CREATE TYPE report_reason AS ENUM ('wrong_info', 'closed_permanently', 'wrong_photo', 'wrong_position', 'duplicate', 'other');
CREATE TYPE report_status AS ENUM ('open', 'in_review', 'resolved', 'rejected');
CREATE TYPE contact_type AS ENUM ('phone', 'whatsapp', 'email', 'website', 'vhf', 'instagram', 'facebook');
CREATE TYPE media_type AS ENUM ('photo', 'video', 'logo', 'document');
CREATE TYPE price_tier AS ENUM ('free', 'paid', 'unknown');
CREATE TYPE actor_type AS ENUM ('user', 'admin', 'system');
CREATE TYPE notification_type AS ENUM ('booking_status', 'new_photo', 'new_review', 'favorite_update', 'moderation_result', 'system');
CREATE TYPE admin_area_level AS ENUM ('region', 'province', 'district');
CREATE TYPE water_body_type AS ENUM ('bay', 'cove', 'gulf', 'strait', 'channel');
CREATE TYPE contribution_type AS ENUM ('review_created', 'photo_approved', 'suggestion_approved', 'report_confirmed');

-- ---------------------------------------------------------------------
-- 2. ORTAK FONKSİYONLAR
-- ---------------------------------------------------------------------

-- updated_at kolonu her yazımda otomatik yenilenir (§5 giriş notu).
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$fn$;

-- to_tsvector(regconfig, text) STABLE'dır (regconfig ALTER edilebilir
-- olduğu için); GENERATED ALWAYS ... STORED yalnızca IMMUTABLE ifadeler
-- kabul eder. 'simple' konfigürasyonu pratikte hiç değişmediğinden bu
-- ince sarmalayıcı güvenle IMMUTABLE işaretlenir (locations.search_text
-- generated kolonunun tek çalışır yolu budur).
CREATE OR REPLACE FUNCTION immutable_simple_tsvector(p_text text) RETURNS tsvector
LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $fn$
  SELECT to_tsvector('simple', p_text);
$fn$;

-- ---------------------------------------------------------------------
-- 3. LOOKUP TABLOLARI (§4) + i18n (§1.6)
-- ---------------------------------------------------------------------

CREATE TABLE roles (
  id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        TEXT NOT NULL,
  permissions JSONB NOT NULL DEFAULT '{}'::jsonb,
  sort_order  SMALLINT,
  is_active   BOOLEAN NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_roles_code UNIQUE (code)
);

CREATE TABLE currencies (
  code           CHAR(3) PRIMARY KEY,
  symbol         TEXT NOT NULL,
  decimal_digits SMALLINT NOT NULL DEFAULT 2,
  sort_order     SMALLINT,
  is_active      BOOLEAN NOT NULL DEFAULT true,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE location_types (
  id                    SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code                  TEXT NOT NULL,
  icon_key              TEXT,
  color_hex             CHAR(7),
  supports_reservation  BOOLEAN NOT NULL DEFAULT false,
  sort_order            SMALLINT,
  is_active             BOOLEAN NOT NULL DEFAULT true,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_location_types_code UNIQUE (code)
);

CREATE TABLE location_type_i18n (
  location_type_id SMALLINT NOT NULL REFERENCES location_types (id) ON DELETE CASCADE,
  locale           TEXT NOT NULL,
  name             TEXT NOT NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (location_type_id, locale)
);

CREATE TABLE boat_types (
  id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        TEXT NOT NULL,
  icon_key    TEXT,
  sort_order  SMALLINT,
  is_active   BOOLEAN NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_boat_types_code UNIQUE (code)
);

CREATE TABLE boat_type_i18n (
  boat_type_id SMALLINT NOT NULL REFERENCES boat_types (id) ON DELETE CASCADE,
  locale       TEXT NOT NULL,
  name         TEXT NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (boat_type_id, locale)
);

CREATE TABLE engine_types (
  id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        TEXT NOT NULL,
  sort_order  SMALLINT,
  is_active   BOOLEAN NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_engine_types_code UNIQUE (code)
);

CREATE TABLE amenities (
  id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        TEXT NOT NULL,
  icon_key    TEXT,
  category    TEXT,
  sort_order  SMALLINT,
  is_active   BOOLEAN NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_amenities_code UNIQUE (code),
  CONSTRAINT ck_amenities_category CHECK (category IS NULL OR category IN ('utility', 'comfort', 'food', 'safety'))
);

CREATE TABLE amenity_i18n (
  amenity_id SMALLINT NOT NULL REFERENCES amenities (id) ON DELETE CASCADE,
  locale     TEXT NOT NULL,
  name       TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (amenity_id, locale)
);

CREATE TABLE services (
  id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        TEXT NOT NULL,
  icon_key    TEXT,
  sort_order  SMALLINT,
  is_active   BOOLEAN NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_services_code UNIQUE (code)
);

CREATE TABLE service_i18n (
  service_id SMALLINT NOT NULL REFERENCES services (id) ON DELETE CASCADE,
  locale     TEXT NOT NULL,
  name       TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (service_id, locale)
);

CREATE TABLE rating_dimensions (
  id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        TEXT NOT NULL,
  sort_order  SMALLINT,
  is_active   BOOLEAN NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_rating_dimensions_code UNIQUE (code)
);

CREATE TABLE rating_dimension_i18n (
  rating_dimension_id SMALLINT NOT NULL REFERENCES rating_dimensions (id) ON DELETE CASCADE,
  locale              TEXT NOT NULL,
  name                TEXT NOT NULL,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (rating_dimension_id, locale)
);

-- ---------------------------------------------------------------------
-- 4. GEO (§5.5)
-- ---------------------------------------------------------------------

CREATE TABLE countries (
  code                    CHAR(2) PRIMARY KEY,
  iso3                    CHAR(3) NOT NULL,
  name                    TEXT NOT NULL,
  default_currency_code   CHAR(3) REFERENCES currencies (code),
  default_locale          TEXT NOT NULL DEFAULT 'tr',
  phone_prefix            TEXT,
  is_active               BOOLEAN NOT NULL DEFAULT false,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_countries_iso3 UNIQUE (iso3)
);

CREATE TABLE admin_areas (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  country_code  CHAR(2) NOT NULL REFERENCES countries (code),
  parent_id     UUID REFERENCES admin_areas (id),
  level         admin_area_level NOT NULL,
  name          TEXT NOT NULL,
  slug          TEXT,
  centroid      geography(Point, 4326),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_admin_areas_country_level_slug UNIQUE (country_code, level, slug),
  CONSTRAINT ck_admin_areas_region_no_parent CHECK (level <> 'region' OR parent_id IS NULL)
);

-- district'in parent'ı province olmalı: bu, parent satırının level'ına
-- bakmayı gerektirir (satır-içi CHECK ile ifade edilemez) → trigger.
CREATE OR REPLACE FUNCTION trg_check_admin_area_hierarchy() RETURNS trigger
LANGUAGE plpgsql AS $fn$
DECLARE
  v_parent_level admin_area_level;
BEGIN
  IF NEW.level = 'district' THEN
    IF NEW.parent_id IS NULL THEN
      RAISE EXCEPTION 'district seviyesindeki admin_area için parent_id (province) zorunludur';
    END IF;
    SELECT level INTO v_parent_level FROM admin_areas WHERE id = NEW.parent_id;
    IF v_parent_level IS DISTINCT FROM 'province' THEN
      RAISE EXCEPTION 'district admin_area''in parent''ı province olmalıdır (bulunan seviye: %)', v_parent_level;
    END IF;
  END IF;
  RETURN NEW;
END;
$fn$;

CREATE TRIGGER trg_admin_areas_hierarchy
  BEFORE INSERT OR UPDATE ON admin_areas
  FOR EACH ROW EXECUTE FUNCTION trg_check_admin_area_hierarchy();

CREATE TABLE admin_area_i18n (
  admin_area_id UUID NOT NULL REFERENCES admin_areas (id) ON DELETE CASCADE,
  locale        TEXT NOT NULL,
  name          TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (admin_area_id, locale)
);

CREATE TABLE water_bodies (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  country_code  CHAR(2) REFERENCES countries (code),
  type          water_body_type NOT NULL,
  name          TEXT NOT NULL,
  slug          TEXT,
  centroid      geography(Point, 4326),
  boundary      geography(Polygon, 4326),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_water_bodies_slug UNIQUE (slug)
);

-- ---------------------------------------------------------------------
-- 5. IDENTITY ÇEKİRDEĞİ (§5.1–5.4) + ADR-001 (user_sessions, idempotency_keys)
--    Not: media (community) ve boats burada erken kurulur çünkü
--    catalog.locations bunlara FK verir (döngüsel bağımlılığı önler).
-- ---------------------------------------------------------------------

CREATE TABLE users (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  firebase_uid        TEXT NOT NULL,
  email               CITEXT,
  email_verified_at   TIMESTAMPTZ,
  phone               TEXT,
  phone_verified_at   TIMESTAMPTZ,
  role_id             SMALLINT NOT NULL DEFAULT 1 REFERENCES roles (id),
  status              user_status NOT NULL DEFAULT 'active',
  locale              TEXT NOT NULL DEFAULT 'tr',
  country_code        CHAR(2) NOT NULL DEFAULT 'TR' REFERENCES countries (code),
  is_guest            BOOLEAN NOT NULL DEFAULT false,
  last_sign_in_at     TIMESTAMPTZ,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at          TIMESTAMPTZ,
  deleted_by          UUID REFERENCES users (id),
  CONSTRAINT ux_users_firebase_uid UNIQUE (firebase_uid),
  CONSTRAINT ck_users_phone_e164 CHECK (phone IS NULL OR phone ~ '^\+[1-9][0-9]{1,14}$')
);

CREATE UNIQUE INDEX ux_users_email ON users (email) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX ux_users_phone ON users (phone) WHERE deleted_at IS NULL;

CREATE TABLE media (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  media_type          media_type NOT NULL DEFAULT 'photo',
  uploader_user_id    UUID REFERENCES users (id),
  storage_key         TEXT NOT NULL,
  mime_type           TEXT NOT NULL,
  width               INTEGER,
  height              INTEGER,
  size_bytes          INTEGER,
  blurhash            TEXT,
  taken_at            TIMESTAMPTZ,
  moderation_status   moderation_status NOT NULL DEFAULT 'pending',
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at          TIMESTAMPTZ,
  deleted_by          UUID REFERENCES users (id),
  CONSTRAINT ux_media_storage_key UNIQUE (storage_key),
  CONSTRAINT ck_media_mime_type CHECK (mime_type IN ('image/jpeg', 'image/png', 'image/webp', 'video/mp4', 'application/pdf')),
  CONSTRAINT ck_media_width_positive CHECK (width IS NULL OR width > 0),
  CONSTRAINT ck_media_height_positive CHECK (height IS NULL OR height > 0),
  CONSTRAINT ck_media_size_bytes_positive CHECK (size_bytes IS NULL OR size_bytes > 0)
);

-- user_profiles.home_port_location_id → locations henüz yok (catalog
-- aşamasında oluşacak); FK, locations tablosu kurulduktan sonra
-- ALTER TABLE ile eklenir (bkz. §7 bloğu).
CREATE TABLE user_profiles (
  user_id                 UUID PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
  display_name            TEXT NOT NULL,
  full_name               TEXT,
  avatar_media_id         UUID REFERENCES media (id),
  bio                     TEXT,
  home_port_location_id   UUID,
  experience_years        SMALLINT,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_user_profiles_bio_length CHECK (bio IS NULL OR char_length(bio) <= 500)
);

CREATE TABLE user_settings (
  user_id                 UUID PRIMARY KEY REFERENCES users (id),
  theme                   TEXT,
  units                   TEXT NOT NULL DEFAULT 'metric',
  marketing_consent_at    TIMESTAMPTZ,
  terms_accepted_at       TIMESTAMPTZ NOT NULL,
  privacy_accepted_at     TIMESTAMPTZ NOT NULL,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_user_settings_theme CHECK (theme IS NULL OR theme IN ('system', 'light', 'dark')),
  CONSTRAINT ck_user_settings_units CHECK (units IN ('metric', 'imperial'))
);

CREATE TABLE user_devices (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES users (id),
  fcm_token     TEXT NOT NULL,
  platform      TEXT,
  app_version   TEXT,
  os_version    TEXT,
  locale        TEXT,
  last_seen_at  TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_user_devices_fcm_token UNIQUE (fcm_token),
  CONSTRAINT ck_user_devices_platform CHECK (platform IS NULL OR platform IN ('ios', 'android'))
);

-- ADR-001: refresh-token rotasyonu / reuse-detection oturum tablosu.
CREATE TABLE user_sessions (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id             UUID NOT NULL REFERENCES users (id),
  token_hash          TEXT NOT NULL,
  family_id           UUID NOT NULL,
  rotated_from_id     UUID REFERENCES user_sessions (id),
  issued_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at          TIMESTAMPTZ NOT NULL,
  revoked_at          TIMESTAMPTZ,
  reuse_detected_at   TIMESTAMPTZ,
  ip                  INET,
  user_agent          TEXT,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_user_sessions_token_hash UNIQUE (token_hash)
);

-- ADR-001: idempotency anahtarları — yanıt önbelleği, güncellenmez (append-only cache).
CREATE TABLE idempotency_keys (
  user_id           UUID REFERENCES users (id),
  idem_key          TEXT NOT NULL,
  request_hash      TEXT NOT NULL,
  response_status   SMALLINT,
  response_body     JSONB,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at        TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (user_id, idem_key)
);

CREATE TABLE boats (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_user_id       UUID NOT NULL REFERENCES users (id),
  name                TEXT NOT NULL,
  boat_type_id        SMALLINT NOT NULL REFERENCES boat_types (id),
  brand               TEXT,
  model               TEXT,
  build_year          SMALLINT,
  length_m            NUMERIC(5, 2) NOT NULL,
  beam_m              NUMERIC(4, 2),
  draft_m             NUMERIC(4, 2),
  engine_type_id      SMALLINT REFERENCES engine_types (id),
  flag_country_code   CHAR(2) REFERENCES countries (code),
  registration_no     TEXT,
  is_primary          BOOLEAN NOT NULL DEFAULT false,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at          TIMESTAMPTZ,
  deleted_by          UUID REFERENCES users (id),
  CONSTRAINT ck_boats_build_year CHECK (build_year IS NULL OR (build_year BETWEEN 1900 AND (EXTRACT(YEAR FROM now())::INT + 1))),
  CONSTRAINT ck_boats_length_m CHECK (length_m BETWEEN 1 AND 200)
);

CREATE UNIQUE INDEX ux_boats_primary ON boats (owner_user_id) WHERE is_primary AND deleted_at IS NULL;

-- ---------------------------------------------------------------------
-- 6. CATALOG (§5.6–§5.8)
-- ---------------------------------------------------------------------

CREATE TABLE locations (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug                TEXT NOT NULL,
  location_type_id    SMALLINT NOT NULL REFERENCES location_types (id),
  status              location_status NOT NULL DEFAULT 'draft',
  country_code        CHAR(2) NOT NULL REFERENCES countries (code),
  admin_area_id       UUID REFERENCES admin_areas (id),
  water_body_id       UUID REFERENCES water_bodies (id),
  name                TEXT NOT NULL,
  description         TEXT,
  position            geography(Point, 4326) NOT NULL,
  max_boat_length_m   NUMERIC(5, 2),
  max_draft_m         NUMERIC(4, 2),
  depth_min_m         NUMERIC(4, 2),
  depth_max_m         NUMERIC(4, 2),
  capacity            INTEGER,
  price_tier          price_tier NOT NULL DEFAULT 'unknown',
  is_24h              BOOLEAN NOT NULL DEFAULT false,
  cover_media_id      UUID REFERENCES media (id),
  rating_avg          NUMERIC(3, 2),
  rating_count        INTEGER NOT NULL DEFAULT 0,
  review_count        INTEGER NOT NULL DEFAULT 0,
  photo_count         INTEGER NOT NULL DEFAULT 0,
  search_text         tsvector GENERATED ALWAYS AS (immutable_simple_tsvector(coalesce(name, '') || ' ' || coalesce(description, ''))) STORED,
  verified_at         TIMESTAMPTZ,
  verified_by         UUID REFERENCES users (id),
  source              TEXT,
  created_by          UUID REFERENCES users (id),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at          TIMESTAMPTZ,
  deleted_by          UUID REFERENCES users (id),
  CONSTRAINT ux_locations_slug UNIQUE (slug),
  CONSTRAINT ck_locations_max_boat_length_m CHECK (max_boat_length_m IS NULL OR max_boat_length_m > 0),
  CONSTRAINT ck_locations_max_draft_m CHECK (max_draft_m IS NULL OR max_draft_m > 0),
  CONSTRAINT ck_locations_depth_range CHECK (depth_min_m IS NULL OR depth_max_m IS NULL OR depth_max_m >= depth_min_m),
  CONSTRAINT ck_locations_source CHECK (source IS NULL OR source IN ('ops_entry', 'user_suggestion', 'import'))
);

-- Döngüsel bağımlılık kapatılıyor: user_profiles.home_port_location_id → locations
ALTER TABLE user_profiles
  ADD CONSTRAINT fk_user_profiles_home_port_location FOREIGN KEY (home_port_location_id) REFERENCES locations (id);

-- --- 6.1 Alt-tip detay tabloları (§5.6.1) ------------------------------

CREATE TABLE marina_details (
  location_id                 UUID PRIMARY KEY REFERENCES locations (id) ON DELETE CASCADE,
  berth_count                 INTEGER,
  vhf_channel                 TEXT,
  has_blue_flag               BOOLEAN,
  travel_lift_capacity_tons   NUMERIC(6, 1),
  crane_capacity_tons         NUMERIC(6, 1),
  winter_storage              BOOLEAN,
  created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE fuel_dock_details (
  location_id     UUID PRIMARY KEY REFERENCES locations (id) ON DELETE CASCADE,
  has_diesel      BOOLEAN,
  has_gasoline    BOOLEAN,
  has_adblue      BOOLEAN,
  min_depth_m     NUMERIC(4, 2),
  payment_note    TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE restaurant_dock_details (
  location_id               UUID PRIMARY KEY REFERENCES locations (id) ON DELETE CASCADE,
  cuisine                   TEXT,
  berth_count_free          INTEGER,
  min_spend_policy          TEXT,
  reservation_recommended   BOOLEAN,
  created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE anchorage_details (
  location_id       UUID PRIMARY KEY REFERENCES locations (id) ON DELETE CASCADE,
  holding_type      TEXT,
  protection_n      SMALLINT,
  protection_s      SMALLINT,
  protection_e      SMALLINT,
  protection_w      SMALLINT,
  swell_exposure    TEXT,
  is_free           BOOLEAN NOT NULL DEFAULT true,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_anchorage_details_holding_type CHECK (holding_type IS NULL OR holding_type IN ('sand', 'mud', 'weed', 'rock', 'mixed')),
  CONSTRAINT ck_anchorage_details_protection_n CHECK (protection_n IS NULL OR protection_n BETWEEN 0 AND 5),
  CONSTRAINT ck_anchorage_details_protection_s CHECK (protection_s IS NULL OR protection_s BETWEEN 0 AND 5),
  CONSTRAINT ck_anchorage_details_protection_e CHECK (protection_e IS NULL OR protection_e BETWEEN 0 AND 5),
  CONSTRAINT ck_anchorage_details_protection_w CHECK (protection_w IS NULL OR protection_w BETWEEN 0 AND 5)
);

-- CHECK tutarlılığı: detay satırı yalnız uygun location_type için eklenebilir (§5.6.1 sonu).
CREATE OR REPLACE FUNCTION trg_check_marina_details_type() RETURNS trigger
LANGUAGE plpgsql AS $fn$
DECLARE v_code TEXT;
BEGIN
  SELECT lt.code INTO v_code FROM locations l JOIN location_types lt ON lt.id = l.location_type_id WHERE l.id = NEW.location_id;
  IF v_code IS NULL OR v_code NOT IN ('private_marina', 'municipal_marina', 'boat_club') THEN
    RAISE EXCEPTION 'marina_details yalnızca private_marina/municipal_marina/boat_club tipli location için eklenebilir (location_id=%, type=%)', NEW.location_id, v_code;
  END IF;
  RETURN NEW;
END;
$fn$;

CREATE TRIGGER trg_marina_details_check_type
  BEFORE INSERT OR UPDATE ON marina_details
  FOR EACH ROW EXECUTE FUNCTION trg_check_marina_details_type();

CREATE OR REPLACE FUNCTION trg_check_fuel_dock_details_type() RETURNS trigger
LANGUAGE plpgsql AS $fn$
DECLARE v_code TEXT;
BEGIN
  SELECT lt.code INTO v_code FROM locations l JOIN location_types lt ON lt.id = l.location_type_id WHERE l.id = NEW.location_id;
  IF v_code IS NULL OR v_code NOT IN ('fuel_pier') THEN
    RAISE EXCEPTION 'fuel_dock_details yalnızca fuel_pier tipli location için eklenebilir (location_id=%, type=%)', NEW.location_id, v_code;
  END IF;
  RETURN NEW;
END;
$fn$;

CREATE TRIGGER trg_fuel_dock_details_check_type
  BEFORE INSERT OR UPDATE ON fuel_dock_details
  FOR EACH ROW EXECUTE FUNCTION trg_check_fuel_dock_details_type();

CREATE OR REPLACE FUNCTION trg_check_restaurant_dock_details_type() RETURNS trigger
LANGUAGE plpgsql AS $fn$
DECLARE v_code TEXT;
BEGIN
  SELECT lt.code INTO v_code FROM locations l JOIN location_types lt ON lt.id = l.location_type_id WHERE l.id = NEW.location_id;
  IF v_code IS NULL OR v_code NOT IN ('restaurant_pier') THEN
    RAISE EXCEPTION 'restaurant_dock_details yalnızca restaurant_pier tipli location için eklenebilir (location_id=%, type=%)', NEW.location_id, v_code;
  END IF;
  RETURN NEW;
END;
$fn$;

CREATE TRIGGER trg_restaurant_dock_details_check_type
  BEFORE INSERT OR UPDATE ON restaurant_dock_details
  FOR EACH ROW EXECUTE FUNCTION trg_check_restaurant_dock_details_type();

CREATE OR REPLACE FUNCTION trg_check_anchorage_details_type() RETURNS trigger
LANGUAGE plpgsql AS $fn$
DECLARE v_code TEXT;
BEGIN
  SELECT lt.code INTO v_code FROM locations l JOIN location_types lt ON lt.id = l.location_type_id WHERE l.id = NEW.location_id;
  IF v_code IS NULL OR v_code NOT IN ('mooring_point', 'buoy', 'guest_mooring') THEN
    RAISE EXCEPTION 'anchorage_details yalnızca mooring_point/buoy/guest_mooring tipli location için eklenebilir (location_id=%, type=%)', NEW.location_id, v_code;
  END IF;
  RETURN NEW;
END;
$fn$;

CREATE TRIGGER trg_anchorage_details_check_type
  BEFORE INSERT OR UPDATE ON anchorage_details
  FOR EACH ROW EXECUTE FUNCTION trg_check_anchorage_details_type();

-- --- 6.2 İletişim, saat, sezon (§5.7) ----------------------------------

CREATE TABLE location_contacts (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  location_id    UUID NOT NULL REFERENCES locations (id),
  contact_type   contact_type NOT NULL,
  value          TEXT NOT NULL,
  label          TEXT,
  is_primary     BOOLEAN NOT NULL DEFAULT false,
  is_verified    BOOLEAN NOT NULL DEFAULT false,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_location_contacts_type_value UNIQUE (location_id, contact_type, value)
);

CREATE TABLE operating_hours (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  location_id   UUID NOT NULL REFERENCES locations (id),
  day_of_week   SMALLINT NOT NULL,
  opens_at      TIME,
  closes_at     TIME,
  is_closed     BOOLEAN NOT NULL DEFAULT false,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_operating_hours_day_of_week CHECK (day_of_week BETWEEN 0 AND 6),
  CONSTRAINT ux_operating_hours_day_opens UNIQUE (location_id, day_of_week, opens_at)
);

CREATE TABLE opening_seasons (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  location_id     UUID NOT NULL REFERENCES locations (id),
  opens_on_month  SMALLINT,
  opens_on_day    SMALLINT,
  closes_on_month SMALLINT,
  closes_on_day   SMALLINT,
  note            TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_opening_seasons_opens_on_month CHECK (opens_on_month IS NULL OR opens_on_month BETWEEN 1 AND 12),
  CONSTRAINT ck_opening_seasons_opens_on_day CHECK (opens_on_day IS NULL OR opens_on_day BETWEEN 1 AND 31),
  CONSTRAINT ck_opening_seasons_closes_on_month CHECK (closes_on_month IS NULL OR closes_on_month BETWEEN 1 AND 12),
  CONSTRAINT ck_opening_seasons_closes_on_day CHECK (closes_on_day IS NULL OR closes_on_day BETWEEN 1 AND 31)
);

CREATE TABLE location_i18n (
  location_id  UUID NOT NULL REFERENCES locations (id) ON DELETE CASCADE,
  locale       TEXT NOT NULL,
  name         TEXT,
  description  TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (location_id, locale)
);

-- --- 6.3 Köprüler (§5.8) ------------------------------------------------

CREATE TABLE location_amenities (
  location_id  UUID NOT NULL REFERENCES locations (id),
  amenity_id   SMALLINT NOT NULL REFERENCES amenities (id),
  note         TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (location_id, amenity_id)
);

CREATE TABLE location_services (
  location_id  UUID NOT NULL REFERENCES locations (id),
  service_id   SMALLINT NOT NULL REFERENCES services (id),
  price_note   TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (location_id, service_id)
);

CREATE TABLE location_media (
  location_id  UUID NOT NULL REFERENCES locations (id),
  media_id     UUID NOT NULL REFERENCES media (id),
  sort_order   SMALLINT,
  is_cover     BOOLEAN NOT NULL DEFAULT false,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (location_id, media_id)
);

-- ---------------------------------------------------------------------
-- 7. COMMUNITY (§5.9)
-- ---------------------------------------------------------------------

CREATE TABLE reviews (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  location_id      UUID NOT NULL REFERENCES locations (id),
  user_id          UUID NOT NULL REFERENCES users (id),
  boat_id          UUID REFERENCES boats (id),
  overall_rating   SMALLINT NOT NULL,
  title            TEXT,
  body             TEXT,
  visited_on       DATE,
  status           moderation_status NOT NULL DEFAULT 'pending',
  helpful_count    INTEGER NOT NULL DEFAULT 0,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at       TIMESTAMPTZ,
  deleted_by       UUID REFERENCES users (id),
  CONSTRAINT ck_reviews_overall_rating CHECK (overall_rating BETWEEN 1 AND 5),
  CONSTRAINT ck_reviews_body_length CHECK (body IS NULL OR char_length(body) <= 4000)
);

CREATE UNIQUE INDEX ux_reviews_location_user ON reviews (location_id, user_id) WHERE deleted_at IS NULL;

CREATE TABLE review_media (
  review_id   UUID NOT NULL REFERENCES reviews (id),
  media_id    UUID NOT NULL REFERENCES media (id),
  sort_order  SMALLINT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (review_id, media_id)
);

CREATE TABLE review_ratings (
  review_id     UUID NOT NULL REFERENCES reviews (id),
  dimension_id  SMALLINT NOT NULL REFERENCES rating_dimensions (id),
  score         SMALLINT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (review_id, dimension_id),
  CONSTRAINT ck_review_ratings_score CHECK (score BETWEEN 1 AND 5)
);

CREATE TABLE review_reactions (
  review_id  UUID NOT NULL REFERENCES reviews (id),
  user_id    UUID NOT NULL REFERENCES users (id),
  reaction   TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (review_id, user_id, reaction),
  CONSTRAINT ck_review_reactions_reaction CHECK (reaction = 'helpful')
);

CREATE TABLE boat_media (
  boat_id     UUID NOT NULL REFERENCES boats (id),
  media_id    UUID NOT NULL REFERENCES media (id),
  is_cover    BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (boat_id, media_id)
);

CREATE TABLE favorites (
  user_id      UUID NOT NULL REFERENCES users (id),
  location_id  UUID NOT NULL REFERENCES locations (id),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, location_id)
);

CREATE TABLE recently_viewed (
  user_id         UUID NOT NULL REFERENCES users (id),
  location_id     UUID NOT NULL REFERENCES locations (id),
  last_viewed_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  view_count      INTEGER NOT NULL DEFAULT 1,
  PRIMARY KEY (user_id, location_id)
);

CREATE TABLE suggested_locations (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id               UUID NOT NULL REFERENCES users (id),
  name                  TEXT NOT NULL,
  location_type_id      SMALLINT REFERENCES location_types (id),
  position              geography(Point, 4326) NOT NULL,
  note                  TEXT,
  status                moderation_status NOT NULL DEFAULT 'pending',
  reviewed_by           UUID REFERENCES users (id),
  reviewed_at           TIMESTAMPTZ,
  created_location_id   UUID REFERENCES locations (id),
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at            TIMESTAMPTZ,
  deleted_by            UUID REFERENCES users (id)
);

CREATE TABLE location_reports (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           UUID REFERENCES users (id),
  location_id       UUID NOT NULL REFERENCES locations (id),
  reason            report_reason NOT NULL,
  message           TEXT,
  status            report_status NOT NULL DEFAULT 'open',
  resolved_by       UUID REFERENCES users (id),
  resolved_at       TIMESTAMPTZ,
  resolution_note   TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- append-only: gerçek olaylar hiç kaybolmaz, güncelleme yapılmaz.
CREATE TABLE contribution_events (
  id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id      UUID NOT NULL REFERENCES users (id),
  type         contribution_type NOT NULL,
  entity_type  TEXT,
  entity_id    UUID,
  points       SMALLINT NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE moderation_tasks (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  entity_type            moderation_entity NOT NULL,
  entity_id              UUID NOT NULL,
  status                 moderation_status NOT NULL DEFAULT 'pending',
  assigned_to_user_id    UUID REFERENCES users (id),
  decided_by_user_id     UUID REFERENCES users (id),
  decided_at             TIMESTAMPTZ,
  decision_note          TEXT,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_moderation_tasks_entity UNIQUE (entity_type, entity_id)
);

-- ---------------------------------------------------------------------
-- 8. BOOKING (§5.9)
-- ---------------------------------------------------------------------

CREATE TABLE reservation_requests (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id              UUID NOT NULL REFERENCES users (id),
  location_id          UUID NOT NULL REFERENCES locations (id),
  boat_id              UUID REFERENCES boats (id),
  boat_name            TEXT NOT NULL,
  boat_length_m        NUMERIC(5, 2) NOT NULL,
  boat_draft_m         NUMERIC(4, 2) NOT NULL,
  check_in_on          DATE NOT NULL,
  check_out_on         DATE NOT NULL,
  contact_phone        TEXT NOT NULL,
  note                 TEXT,
  status               reservation_request_status NOT NULL DEFAULT 'pending',
  handled_by_user_id   UUID REFERENCES users (id),
  expires_at           TIMESTAMPTZ,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at           TIMESTAMPTZ,
  deleted_by           UUID REFERENCES users (id),
  CONSTRAINT ck_reservation_requests_dates CHECK (check_out_on > check_in_on),
  CONSTRAINT ck_reservation_requests_note_length CHECK (note IS NULL OR char_length(note) <= 1000),
  CONSTRAINT ck_reservation_requests_contact_phone CHECK (contact_phone ~ '^\+[1-9][0-9]{1,14}$')
);

-- check_in_on >= CURRENT_DATE yalnızca INSERT anında geçerlidir (§5.9);
-- normal CHECK constraint olsaydı tarih geçtikçe eski satırların
-- UPDATE'i (ör. status değişimi) haksız yere reddedilirdi.
CREATE OR REPLACE FUNCTION trg_check_reservation_request_checkin() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  IF NEW.check_in_on < CURRENT_DATE THEN
    RAISE EXCEPTION 'check_in_on geçmiş bir tarih olamaz (check_in_on=%)', NEW.check_in_on;
  END IF;
  RETURN NEW;
END;
$fn$;

CREATE TRIGGER trg_reservation_requests_checkin_insert
  BEFORE INSERT ON reservation_requests
  FOR EACH ROW EXECUTE FUNCTION trg_check_reservation_request_checkin();

-- append-only durum geçmişi.
CREATE TABLE reservation_request_events (
  id             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  request_id     UUID NOT NULL REFERENCES reservation_requests (id) ON DELETE CASCADE,
  from_status    reservation_request_status,
  to_status      reservation_request_status NOT NULL,
  actor_type     actor_type NOT NULL,
  actor_user_id  UUID REFERENCES users (id),
  note           TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- 9. MESSAGING (§5.9)
-- ---------------------------------------------------------------------

CREATE TABLE notifications (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES users (id),
  type        notification_type NOT NULL,
  title       TEXT,
  body        TEXT,
  data        JSONB,
  read_at     TIMESTAMPTZ,
  pushed_at   TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE notification_preferences (
  user_id        UUID NOT NULL REFERENCES users (id),
  type           notification_type NOT NULL,
  push_enabled   BOOLEAN NOT NULL DEFAULT true,
  email_enabled  BOOLEAN NOT NULL DEFAULT true,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, type)
);

-- ---------------------------------------------------------------------
-- 10. OPS (§5.10)
-- ---------------------------------------------------------------------

-- append-only, aylık RANGE partition. PK partition anahtarını (occurred_at) içermelidir.
CREATE TABLE audit_logs (
  id            BIGINT GENERATED ALWAYS AS IDENTITY,
  occurred_at   TIMESTAMPTZ NOT NULL,
  actor_type    actor_type NOT NULL,
  actor_user_id UUID REFERENCES users (id),
  action        TEXT NOT NULL,
  entity_type   TEXT,
  entity_id     UUID,
  old_values    JSONB,
  new_values    JSONB,
  ip            INET,
  user_agent    TEXT,
  request_id    UUID,
  PRIMARY KEY (id, occurred_at)
) PARTITION BY RANGE (occurred_at);

CREATE TABLE audit_logs_2026_07 PARTITION OF audit_logs FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE audit_logs_2026_08 PARTITION OF audit_logs FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE audit_logs_2026_09 PARTITION OF audit_logs FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE audit_logs_2026_10 PARTITION OF audit_logs FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
CREATE TABLE audit_logs_2026_11 PARTITION OF audit_logs FOR VALUES FROM ('2026-11-01') TO ('2026-12-01');
CREATE TABLE audit_logs_2026_12 PARTITION OF audit_logs FOR VALUES FROM ('2026-12-01') TO ('2027-01-01');
CREATE TABLE audit_logs_default PARTITION OF audit_logs DEFAULT;

CREATE TABLE app_settings (
  key          TEXT PRIMARY KEY,
  value        JSONB NOT NULL,
  description  TEXT,
  updated_by   UUID REFERENCES users (id),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =====================================================================
-- 11. INDEX'LER (§6)
-- =====================================================================

-- locations — haritanın ana sorgusu ve arama
CREATE INDEX ix_locations_position ON locations USING GIST (position);
CREATE INDEX ix_locations_search_text ON locations USING GIN (search_text);
CREATE INDEX ix_locations_name_trgm ON locations USING GIN (name gin_trgm_ops);
CREATE INDEX ix_locations_type_status ON locations (location_type_id, status) WHERE deleted_at IS NULL;
CREATE INDEX ix_locations_admin_area ON locations (admin_area_id);
CREATE INDEX ix_locations_water_body ON locations (water_body_id);
CREATE INDEX ix_locations_country_status ON locations (country_code, status);
CREATE INDEX ix_locations_rating_avg ON locations (rating_avg DESC) WHERE status = 'published' AND deleted_at IS NULL;
CREATE INDEX ix_locations_created_at ON locations (created_at DESC) WHERE status = 'published';
CREATE INDEX ix_locations_cover_media ON locations (cover_media_id);
CREATE INDEX ix_locations_created_by ON locations (created_by);
CREATE INDEX ix_locations_verified_by ON locations (verified_by);
CREATE INDEX ix_locations_deleted_by ON locations (deleted_by);

-- reviews
CREATE INDEX ix_reviews_location_status_created ON reviews (location_id, status, created_at DESC);
CREATE INDEX ix_reviews_user_created ON reviews (user_id, created_at DESC);
CREATE INDEX ix_reviews_boat ON reviews (boat_id);
CREATE INDEX ix_reviews_deleted_by ON reviews (deleted_by);

-- reservation_requests
CREATE INDEX ix_reservation_requests_user_created ON reservation_requests (user_id, created_at DESC);
CREATE INDEX ix_reservation_requests_status_created ON reservation_requests (status, created_at);
CREATE INDEX ix_reservation_requests_location ON reservation_requests (location_id);
CREATE INDEX ix_reservation_requests_boat ON reservation_requests (boat_id);
CREATE INDEX ix_reservation_requests_handled_by ON reservation_requests (handled_by_user_id);
CREATE INDEX ix_reservation_requests_deleted_by ON reservation_requests (deleted_by);

-- notifications
CREATE INDEX ix_notifications_user_created ON notifications (user_id, created_at DESC);
CREATE INDEX ix_notifications_user_unread ON notifications (user_id, read_at) WHERE read_at IS NULL;

-- ops kuyrukları
CREATE INDEX ix_moderation_tasks_status_created ON moderation_tasks (status, created_at);
CREATE INDEX ix_moderation_tasks_assigned_to ON moderation_tasks (assigned_to_user_id);
CREATE INDEX ix_moderation_tasks_decided_by ON moderation_tasks (decided_by_user_id);
CREATE INDEX ix_location_reports_status_created ON location_reports (status, created_at);
CREATE INDEX ix_location_reports_user ON location_reports (user_id);
CREATE INDEX ix_location_reports_location ON location_reports (location_id);
CREATE INDEX ix_location_reports_resolved_by ON location_reports (resolved_by);

-- audit_logs — her partition'a otomatik yayılır (PG11+ partitioned index)
CREATE INDEX ix_audit_logs_entity ON audit_logs (entity_type, entity_id);
CREATE INDEX ix_audit_logs_actor_user ON audit_logs (actor_user_id);

-- geo
CREATE INDEX ix_admin_areas_country ON admin_areas (country_code);
CREATE INDEX ix_admin_areas_parent ON admin_areas (parent_id);
CREATE INDEX ix_water_bodies_country ON water_bodies (country_code);
CREATE INDEX ix_countries_default_currency ON countries (default_currency_code);

-- identity
CREATE INDEX ix_users_role ON users (role_id);
CREATE INDEX ix_users_country ON users (country_code);
CREATE INDEX ix_users_deleted_by ON users (deleted_by);
CREATE INDEX ix_user_profiles_avatar_media ON user_profiles (avatar_media_id);
CREATE INDEX ix_user_profiles_home_port ON user_profiles (home_port_location_id);
CREATE INDEX ix_user_devices_user ON user_devices (user_id);
CREATE INDEX ix_user_sessions_user ON user_sessions (user_id);
CREATE INDEX ix_user_sessions_family ON user_sessions (family_id);
CREATE INDEX ix_user_sessions_expires ON user_sessions (expires_at);
CREATE INDEX ix_user_sessions_rotated_from ON user_sessions (rotated_from_id);
CREATE INDEX ix_idempotency_keys_expires ON idempotency_keys (expires_at);

-- boats
CREATE INDEX ix_boats_owner ON boats (owner_user_id);
CREATE INDEX ix_boats_boat_type ON boats (boat_type_id);
CREATE INDEX ix_boats_engine_type ON boats (engine_type_id);
CREATE INDEX ix_boats_flag_country ON boats (flag_country_code);
CREATE INDEX ix_boats_deleted_by ON boats (deleted_by);

-- media
CREATE INDEX ix_media_uploader ON media (uploader_user_id);
CREATE INDEX ix_media_deleted_by ON media (deleted_by);

-- catalog köprüleri
CREATE INDEX ix_location_amenities_amenity ON location_amenities (amenity_id);
CREATE INDEX ix_location_services_service ON location_services (service_id);
CREATE INDEX ix_location_media_media ON location_media (media_id);
CREATE INDEX ix_review_media_media ON review_media (media_id);
CREATE INDEX ix_review_ratings_dimension ON review_ratings (dimension_id);
CREATE INDEX ix_review_reactions_user ON review_reactions (user_id);
CREATE INDEX ix_boat_media_media ON boat_media (media_id);
CREATE INDEX ix_favorites_location ON favorites (location_id);
CREATE INDEX ix_recently_viewed_location ON recently_viewed (location_id);
CREATE INDEX ix_opening_seasons_location ON opening_seasons (location_id);

-- community
CREATE INDEX ix_suggested_locations_user ON suggested_locations (user_id);
CREATE INDEX ix_suggested_locations_type ON suggested_locations (location_type_id);
CREATE INDEX ix_suggested_locations_reviewed_by ON suggested_locations (reviewed_by);
CREATE INDEX ix_suggested_locations_created_location ON suggested_locations (created_location_id);
CREATE INDEX ix_suggested_locations_deleted_by ON suggested_locations (deleted_by);
CREATE INDEX ix_contribution_events_user ON contribution_events (user_id);
CREATE INDEX ix_reservation_request_events_request ON reservation_request_events (request_id);
CREATE INDEX ix_reservation_request_events_actor ON reservation_request_events (actor_user_id);

-- ops
CREATE INDEX ix_app_settings_updated_by ON app_settings (updated_by);

-- =====================================================================
-- 12. TRIGGER'LAR — set_updated_at (append-only / immutable tablolar hariç tümü)
-- =====================================================================

CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON roles FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON currencies FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON location_types FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON location_type_i18n FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON boat_types FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON boat_type_i18n FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON engine_types FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON amenities FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON amenity_i18n FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON services FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON service_i18n FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON rating_dimensions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON rating_dimension_i18n FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON countries FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON admin_areas FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON admin_area_i18n FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON water_bodies FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON media FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON user_profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON user_settings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON user_devices FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON user_sessions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON boats FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON locations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON marina_details FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON fuel_dock_details FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON restaurant_dock_details FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON anchorage_details FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON location_contacts FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON operating_hours FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON opening_seasons FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON location_i18n FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON location_amenities FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON location_services FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON location_media FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON reviews FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON review_media FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON review_ratings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON review_reactions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON boat_media FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON favorites FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON suggested_locations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON location_reports FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON moderation_tasks FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON reservation_requests FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON notifications FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON notification_preferences FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON app_settings FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Not: recently_viewed (last_viewed_at UPSERT ile uygulama tarafından yönetilir),
-- contribution_events / reservation_request_events / audit_logs (append-only)
-- ve idempotency_keys (immutable cache) generic updated_at trigger'ı almaz.

-- --- 12.1 İş kuralı trigger'ları ---------------------------------------

-- (b) reviews → locations.rating_avg / rating_count / review_count
-- (yalnız status='approved' AND deleted_at IS NULL olan yorumlar sayılır)
CREATE OR REPLACE FUNCTION refresh_location_review_stats(p_location_id UUID) RETURNS void
LANGUAGE plpgsql AS $fn$
BEGIN
  UPDATE locations SET
    rating_avg = stats.avg_rating,
    rating_count = stats.cnt,
    review_count = stats.cnt
  FROM (
    SELECT AVG(overall_rating)::numeric(3, 2) AS avg_rating, COUNT(*)::int AS cnt
    FROM reviews
    WHERE location_id = p_location_id AND status = 'approved' AND deleted_at IS NULL
  ) AS stats
  WHERE locations.id = p_location_id;
END;
$fn$;

CREATE OR REPLACE FUNCTION trg_reviews_refresh_location_stats() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  IF TG_OP = 'DELETE' THEN
    PERFORM refresh_location_review_stats(OLD.location_id);
  ELSIF TG_OP = 'UPDATE' THEN
    PERFORM refresh_location_review_stats(NEW.location_id);
    IF NEW.location_id IS DISTINCT FROM OLD.location_id THEN
      PERFORM refresh_location_review_stats(OLD.location_id);
    END IF;
  ELSE
    PERFORM refresh_location_review_stats(NEW.location_id);
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$fn$;

CREATE TRIGGER trg_reviews_stats
  AFTER INSERT OR UPDATE OR DELETE ON reviews
  FOR EACH ROW EXECUTE FUNCTION trg_reviews_refresh_location_stats();

-- (c) location_media değişince locations.photo_count güncelle (yalnız approved medya)
CREATE OR REPLACE FUNCTION trg_location_media_refresh_photo_count() RETURNS trigger
LANGUAGE plpgsql AS $fn$
DECLARE
  v_location_id UUID;
BEGIN
  v_location_id := COALESCE(NEW.location_id, OLD.location_id);
  UPDATE locations SET photo_count = (
    SELECT COUNT(*) FROM location_media lm
    JOIN media m ON m.id = lm.media_id
    WHERE lm.location_id = v_location_id AND m.moderation_status = 'approved' AND m.deleted_at IS NULL
  ) WHERE id = v_location_id;
  RETURN COALESCE(NEW, OLD);
END;
$fn$;

CREATE TRIGGER trg_location_media_photo_count
  AFTER INSERT OR UPDATE OR DELETE ON location_media
  FOR EACH ROW EXECUTE FUNCTION trg_location_media_refresh_photo_count();

-- (d) review_reactions → reviews.helpful_count
CREATE OR REPLACE FUNCTION trg_review_reactions_refresh_helpful_count() RETURNS trigger
LANGUAGE plpgsql AS $fn$
DECLARE
  v_review_id UUID;
BEGIN
  v_review_id := COALESCE(NEW.review_id, OLD.review_id);
  UPDATE reviews SET helpful_count = (
    SELECT COUNT(*) FROM review_reactions WHERE review_id = v_review_id AND reaction = 'helpful'
  ) WHERE id = v_review_id;
  RETURN COALESCE(NEW, OLD);
END;
$fn$;

CREATE TRIGGER trg_review_reactions_helpful_count
  AFTER INSERT OR UPDATE OR DELETE ON review_reactions
  FOR EACH ROW EXECUTE FUNCTION trg_review_reactions_refresh_helpful_count();

-- =====================================================================
-- 13. RLS
-- =====================================================================
-- RLS: Faz 2 (ADR-003)

-- =====================================================================
-- Migration sonu — 0001_init
-- =====================================================================
